remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

title: Klio Creative User Flows
description: Interactive documentation of user flows and system interactions
logo: 
show_downloads: false

# Navigation
nav:
  - name: Home
    link: /klio-flows/
  - name: Freelancer Flows
    link: /klio-flows/freelancer_technical_flow.html
  - name: Agency Flows
    link: /klio-flows/agency_technical_flow.html
  - name: Admin Flows
    link: /klio-flows/admin_technical_flow.html

# Theme customization
github:
  is_project_page: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

# Mermaid settings
mermaid:
  version: "9.4.3"

# Additional settings
exclude: [README.md]
include: 
  - _layouts
  - assets

# Sass settings
sass:
  style: compressed
